MEKALA SUJAN - 21BCE5590


mekala.sujan2021@vitstudent.ac.in

In [1]:
import numpy as np
import pandas as pd

TASK-01 #Creating a Data Frame

In [2]:
d = {'NAME':['Sujan','Naman','Priya','Uday'],'Age':[25,30,np.nan,22],'Branch':['MECH','EEE','ECE','CSE'],'Salary':[75000,125000,65000,45000]}
df = pd.DataFrame(d)
df

    NAME   Age Branch  Salary
0  Sujan  25.0   MECH   75000
1  Naman  30.0    EEE  125000
2  Priya   NaN    ECE   65000
3   Uday  22.0    CSE   45000

TASK - 02 #Changing the column names

In [12]:
df = df.rename(columns={'Name':'Random Value 1','Value':'Random Value 2','Department':'Random Value 3','Income':'Random Value 4'})
df

  Random Value 1  Random Value 2 Random Value 3  Random Value 4
0          Sujan            25.0           MECH           75000
1          Naman            30.0            EEE          125000
2          Priya             NaN            ECE           65000
3           Uday            22.0            CSE           45000

TASK - 03 #To print the Descriptive Statistics

In [13]:
df.describe()

       Random Value 2  Random Value 4
count        3.000000        4.000000
mean        25.666667    77500.000000
std          4.041452    34034.296428
min         22.000000    45000.000000
25%         23.500000    60000.000000
50%         25.000000    70000.000000
75%         27.500000    87500.000000
max         30.000000   125000.000000

TASK - 04 #Checking for null values and checking data type of columns

In [14]:
df.isnull().any()

Random Value 1    False
Random Value 2     True
Random Value 3    False
Random Value 4    False
dtype: bool

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random Value 1  4 non-null      object
 1   Random Value 2  3 non-null      float64
 2   Random Value 3  4 non-null      object
 3   Random Value 4  4 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 256.0+ bytes

TASK - 05 #Use of loc and iloc methods

In [28]:
df.loc[:,['Random Value 2','Random Value 3']]

   Random Value 2 Random Value 3
0            25.0           MECH
1            30.0            EEE
2             NaN            ECE
3            22.0            CSE

In [19]:
df.iloc[:,1:3]

   Random Value 2 Random Value 3
0            25.0           MECH
1            30.0            EEE
2             NaN            ECE
3            22.0            CSE